# Пакети середовища (лівий бік Dockerfile)
packages = [
    "php84", # >=8.4 snapshot
    "composer",
    "nodejs_22", # Node 22 + npm 11
    "nginx"         # простий статичний проксі для Vite-білду
]

providers = ["php", "node"]      # активує відповідні build-фази

# ---------- Build ----------
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    # кешуємо все, що можна
    "php artisan config:cache route:cache view:cache"
]

# ---------- Start ----------
[start]
cmd = "./entrypoint.sh"
