# nixpacks.toml  (новий)

[variables]
# Явно фіксуємо Node 22—так безпечніше, ніж покладатися на `engines`
NIXPACKS_NODE_VERSION = "22"

# Laravel корінь для Nginx/PHP-FPM (провайдер PHP підхопить автоматично)
NIXPACKS_PHP_ROOT_DIR = "/app/public"

# ---------- install ----------
[phases.install]
cmds = [
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm ci --include=dev"
]

# ---------- build ----------
[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build",
    # факультативно лінкуємо storage і кэшимо конфіг
    "php artisan storage:link || true",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

# ---------- start ----------
# Нічого не прописуємо: старт-команду створить PHP-провайдер
