[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "php84", "php84Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci --omit=dev"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan optimize",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
