[phases.setup]
nixPkgs = ["nodejs_22", "php84", "php84Packages.composer"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "node --version",
    "npm --version",
    "php --version",
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm ci --production=false"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build",
    "php artisan storage:link || true",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan ziggy:generate || true"
]

[start]
cmd = "php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=4096"
