[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_18", "npm-9_x"]
aptPkgs = ["libpng-dev", "libjpeg-dev", "libfreetype6-dev", "libzip-dev", "libicu-dev", "libonig-dev"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "php -m",
    "composer install --no-interaction --prefer-dist --optimize-autoloader",
    "npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build",
    "php artisan storage:link",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan ziggy:generate"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
