[phases.setup]
nixPkgs = ["nodejs_22", "php84", "php84Packages.composer"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm ci --include=dev"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build",
    "php artisan storage:link || true"
]

[start]
cmds = [
    "php artisan migrate --force",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan ziggy:generate || true",
    "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
]

[variables]
NODE_ENV = "production"
