[build]
builder = "nixpacks"

# Pre-deploy міграції окремо, щоб фейл не валив контейнер
[deploy]
preDeployCommand = ["php artisan migrate --force"]
healthcheckPath = "/up"
startCommand     = ""              # пусто → візьме дефолт провайдера PHP
