[build]
builder = "nixpacks"
buildCommand = "php artisan migrate --force && php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan ziggy:generate || true && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "web"
