[build]
builder = "nixpacks"

[deploy]
preDeployCommand = [
    "php artisan migrate --force",
    "php artisan notion:log-deploy --branch=${RAILWAY_GIT_BRANCH:-main} --sha=${RAILWAY_GIT_COMMIT_SHA:-unknown}"
]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
healthcheckPath = "/up"
