# Конфіг-as-code для Railway
[build]
builder = "nixpacks"          # Просимо Railway одразу юзати nixpacks.toml

[deploy]
preDeployCommand = ["php artisan migrate --force"]  # міграції окремо
startCommand = "./entrypoint.sh"                # єдиний старт-скрипт
healthcheckPath = "/"                              # 200 = ок
